---
- hosts: all
  become: yes
  tasks:
  - name: Create directory for git
    file:
      path: /opt/tools
      state: directory
      owner: n00b
      group: n00b
      recurse: yes
      mode: 0775
  - name: clone a repo
    git:
      repo: https://github.com/intelburn/anisble-playground.git
      dest: /opt/tools/ansible-playground
      clone: yes
      update: yes
      force: yes
  - name: run script from cloned repo
    # If you want to run a remote script you need to use the absolute path for the script
    shell: /opt/tools/ansible-playground/Git/test.sh
    args:
      chdir: /opt/tools/ansible-playground/Git/